### ISSUE TITLE
16.04

### ISSUE THREAD

**Issue by brandleesee** [Utappia/iQunix#1]
Will a version based on UBuntu LTS 16.04 be in the pipeline?

Thank you.

**Comment by brandleesee** [comment]
Dead project.

**Comment by cerebrux** [comment]
Not actually :)

**Comment by cerebrux** [comment]
I can not provide a timeline of the release but I will try to release as soon as possible

**Comment by brandleesee** [comment]
I'll jump in as soon as it's available, thank you.

**Comment by cerebrux** [comment]
I'll definitely write a post once its available https://utappia.org/
